In [1]:
from library.Layers import D1FullLayer as Layer
from library.Activations import SigmoidActivation as Sig
from library.Losses import MeanSquaredError as MSE
import numpy as np

In [2]:
l1 = Layer(2, 2, Sig)
l2 = Layer(2, 1, Sig)

In [3]:
print(l1.neurons)
print()
print(l2.neurons)

[[0.6734874  0.83949236 0.71005106]
 [0.18627157 0.90225276 0.07379097]]

[[0.56318899 0.47338289 0.51477689]]


In [4]:
inputs = np.array([-3, 6])
reals = np.array([1])
from1 = l1.calculate(inputs)
print(from1)
from2 = l2.calculate(from1)
print()
print(from2)

[0.9764901 0.9928146]

[0.82269393]


In [5]:
oldmse = MSE.value(reals, from2)

In [31]:
dL_dPred = MSE.derive(reals, from2)
dPred_dH1 = l2.neurons[0][0]*Sig.derive(l2.last_unactivated)
dH1_dW1 = inputs[0]*Sig.derive(l1.last_neurons_unactivated[0])

print(dL_dPred)
print(dPred_dH1)
print(dH1_dW1)

dL_dW1 = dL_dPred*dPred_dH1*dH1_dW1
print(dL_dW1)

-0.3537321422547435
0.08199156778774663
-0.05345821937732705
0.0015504515656301478


In [32]:
l1.neurons[0][0] -= dL_dW1*10
from1 = l1.calculate(inputs)
print(from1)
from2 = l2.calculate(from1)
print()
print(from2)
oldmse - MSE.value(reals, from2) > 0

[0.98266175 0.9928146 ]

[0.82320038]


True