In [1]:
from library.Layers import D1FullLayer as Layr
from library.Activations import SigmoidActivation as Sig
from library.Losses import MeanSquaredError as MSE
from library.Network import Network as Net
import numpy as np

In [2]:
l1 = Layr(2, 2, Sig)
l2 = Layr(2, 1, Sig)

In [3]:
print(l1.neurons)
print()
print(l2.neurons)

[[0.94271233 0.5521326  0.44902537]
 [0.67224335 0.41541393 0.34063954]]

[[0.92240743 0.8540925  0.39118745]]


In [4]:
inputs = np.array([-3, 6])
reals = np.array([1])
from1 = l1.calculate(inputs)
print(from1)
from2 = l2.calculate(from1)
print()
print(from2)

[0.71782208 0.69347015]

[0.83829543]


In [5]:
oldmse = MSE.value(reals, from2)

In [6]:
dL_dPred = MSE.derive(reals, from2)
dPred_dH1 = l2.neurons[0][0]*Sig.derive(l2.last_unactivated)
dH1_dW1 = inputs[0]*Sig.derive(l1.last_neurons_unactivated[0])

print(dL_dPred)
print(dPred_dH1)
print(dH1_dW1)

dL_dW1 = dL_dPred*dPred_dH1*dH1_dW1
print(dL_dW1)

-0.32340914448577474
0.1250380491604437
-0.6076606185347212
0.02457285263243884


In [7]:
l1.neurons[0][0] -= dL_dW1*10
from1 = l1.calculate(inputs)
print(from1)
from2 = l2.calculate(from1)
print()
print(from2)
oldmse - MSE.value(reals, from2) > 0

[0.84169172 0.69347015]

[0.85319185]


True

In [15]:
inputs = np.array([[1,2,3],[0,-1,-2],[-1,-2,-3]])
reals = np.array([1,-1,-1])

n1 = Net(3)
n1.add(Layr, output_size=3, activation_type=Sig)
n1.add(Layr, output_size=5, activation_type=Sig)
n1.add(Layr, output_size=5, activation_type=Sig)
n1.add(Layr, output_size=5, activation_type=Sig)
n1.add(Layr, output_size=4, activation_type=Sig)
n1.add(Layr, output_size=2, activation_type=Sig)
n1.add(Layr, output_size=1, activation_type=Sig)
predicts = n1.predict_many(inputs)
print(predicts)
oldmse = MSE.value(reals, predicts)
newmse = MSE.value(reals, predicts) - 1
oldmse

[[0.76070503]
 [0.76069515]
 [0.76068671]]


2.0857882673038493

In [16]:
count = 10000
while oldmse > newmse and count > 0:
    count -= 1
    oldmse = MSE.value(reals, predicts)
    n1.fit(inputs, reals, MSE, lr=0.5)
    predicts = n1.predict_many(inputs)
    newmse = MSE.value(reals, predicts)
#print(newmse)
#for l in n1.layers:
#    print(l.neurons)
print(predicts)
print(newmse)
print(count)

[[0.5498552 ]
 [0.54994772]
 [0.54995008]]
1.669021219229984
7688
